// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform; // <-- Added semicolon

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyC9kbcryuUYA_rY8yOUkD8aizKdtEcOtx8",
    projectId: "new-project-4205a",
    storageBucket: "new-project-4205a.appspot.com",
    messagingSenderId: "138886506763",
    appId: "1:138886506763:android:ba0091524220636a331a0e",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcwfCcKBGvY892deYiQ45soyDbcAL-WW8',
    appId: '1:274514992002:ios:ae5baa9be24990da00cd9b',
    messagingSenderId: '274514992002',
    projectId: 'flutter-prime-df1c5',
    storageBucket: 'flutter-prime-df1c5.appspot.com',
    androidClientId: '274514992002-3bf319q74c3jhe9ib460dc0ovbnt4og5.apps.googleusercontent.com',
    iosClientId: '274514992002-sir5n1lsl1k41sehrqcd98ek6i7uf0ej.apps.googleusercontent.com',
    iosBundleId: 'dev.vlab.com.localCoin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD7IRy2uyTBVSCURMgU25cg5Nx3mFNdM_0",
    authDomain: "new-project-4205a.firebaseapp.com",
    projectId: "new-project-4205a",
    storageBucket: "new-project-4205a.appspot.com",
    messagingSenderId: "138886506763",
    appId: "1:138886506763:web:90da66811e1daffd331a0e",
    measurementId: "G-CPXG43E6XL"
  );
}
